dependencies:
  - python==3.7.*
  - pip
  - pip:
    - easydict==1.9
    - psutil==5.6.3
    - falcon==2.0.0
    - gunicorn==19.9.0
    - meinheld==1.0.1
    - WebTest==2.0.33

# vim:set ft=yaml sw=2 ts=2:
